development:
  adapter: postgresql
  encoding: unicode 
  host: localhost
  database: mbkmrk 
  pool: 5
  username: neilmarion
  password: root

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mbkmrk 
  pool: 5
  username: neilmarion
  password: root

